<a href="https://colab.research.google.com/github/Nazmul-SWE/ml-learning-notes/blob/main/Wk_2_lab_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy practice

Array

In [ ]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [ ]:
b = np.array([[1, 2], [3, 4]])
print(b)


print(b.shape)   # (2, 2)
print(b.ndim)    # 2
print(b.dtype)   # int64 or int32



[[1 2]
 [3 4]]
(2, 2)
2
int64


In [ ]:
c=np.zeros((3,4))
print(c)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
d=np.ones((3,4))
print(d)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
e = np.arange(1, 11, 1)
print(e)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
l = np.linspace(0, 1, 6)
print(l)

[0.  0.2 0.4 0.6 0.8 1. ]




**Exercise 1 **(quick)

    1.Make a 3×3 array of all 7s
    2.**Make** numbers 1..12 and reshape to (3,4)



In [ ]:
#1
b=np.ones((3,4))
print(b*7)

[[7. 7. 7. 7.]
 [7. 7. 7. 7.]
 [7. 7. 7. 7.]]


In [ ]:
arr = np.arange(1, 13).reshape(3, 4)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


**Indexing, slicing, masking**

In [ ]:
x = np.array([10, 20, 30, 40, 50])
print(x[0])
print(x[-1])

10
50


In [ ]:


# 2D indexing

M = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
M[0, 1]     # 2
M[:, 1]     # column 1
M[1, :]     # row 1
M[0:2, 1:3] # submatrix



array([[2, 3],
       [5, 6]])

In [ ]:

x = np.array([[1,2,3,55,56,57],
             [4,5,6,66,67,68],
             [7,8,9,99,96,97],
             [33,44,50,23,45,23]])
# x[row[b:e] , col[b:e]]
print(x[1:3,2:4])


[[ 6 66]
 [ 9 99]]


In [ ]:


v = np.array([0.2,1.5,-0.7,3.3,2.2])
print(v)
mask = v>1.0
mask


[ 0.2  1.5 -0.7  3.3  2.2]


array([1.5, 3.3, 2.2])

In [ ]:
v[mask==False]


NameError: name 'v' is not defined

In [ ]:


x = np.array([1, 2, 3])
y = np.array([10, 20, 30])

x+y


array([11, 22, 33])

In [ ]:
x*y


array([10, 40, 90])

In [ ]:
x*2

array([2, 4, 6])

#** Pandas**

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('weather.csv')

In [ ]:
df

EST  Temperature  DewPoint  Humidity  Sea Level PressureIn  \
0    1/1/2016           38        23        52                 30.03   
1    1/2/2016           36        18        46                 30.02   
2    1/3/2016           40        21        47                 29.86   
3    1/4/2016           25         9        44                 30.05   
4    1/5/2016           20        -3        41                 30.57   
5    1/6/2016           33         4        35                 30.50   
6    1/7/2016           39        11        33                 30.28   
7    1/8/2016           39        29        64                 30.20   
8    1/9/2016           44        38        77                 30.16   
9   1/10/2016           50        46        71                 29.59   
10  1/11/2016           33         8        37                 29.92   
11  1/12/2016           35        15        53                 29.85   
12  1/13/2016           26         4        42                 29.94   
13  1/14/2016           30        12        47                 29.95   
14  1/15/2016           43        31        62                 29.82   
15  1/16/2016           47        37        70                 29.52   
16  1/17/2016           36        23        66                 29.78   
17  1/18/2016           25         6        53                 29.83   
18  1/19/2016           22         3        42                 30.03   
19  1/20/2016           32        15        49                 30.13   
20  1/21/2016           31        11        45                 30.15   
21  1/22/2016           26         6        41                 30.21   
22  1/23/2016           26        21        78                 29.77   
23  1/24/2016           28        11        53                 29.92   
24  1/25/2016           34        18        54                 30.25   
25  1/26/2016           43        29        56                 30.03   
26  1/27/2016           41        22        45                 30.03   
27  1/28/2016           37        20        51                 29.90   
28  1/29/2016           36        21        50                 29.58   
29  1/30/2016           34        16        46                 30.01   
30  1/31/2016           46        28        52                 29.90   

    VisibilityMiles  WindSpeedMPH PrecipitationIn  CloudCover    Events  \
0                10           8.0               0           5       NaN   
1                10           7.0               0           3       NaN   
2                10           8.0               0           1       NaN   
3                10           9.0               0           3       NaN   
4                10           5.0               0           0       NaN   
5                10           4.0               0           0       NaN   
6                10           2.0               0           3       NaN   
7                10           4.0               0           8       NaN   
8                 9           8.0               T           8      Rain   
9                 4           NaN             1.8           7      Rain   
10               10           NaN               0           1       NaN   
11               10           6.0               T           4       NaN   
12               10          10.0               0           0       NaN   
13               10           5.0               T           7       NaN   
14                9           5.0               T           2       NaN   
15                8           7.0            0.24           7      Rain   
16                8           6.0            0.05           6  Fog-Snow   
17                9          12.0               T           2      Snow   
18               10          11.0               0           1       NaN   
19               10           6.0               0           2       NaN   
20               10           6.0               0           1       NaN   
21                9           NaN            0.01      

In [ ]:


df.head()



EST  Temperature  DewPoint  Humidity  Sea Level PressureIn  \
0  1/1/2016           38        23        52                 30.03   
1  1/2/2016           36        18        46                 30.02   
2  1/3/2016           40        21        47                 29.86   
3  1/4/2016           25         9        44                 30.05   
4  1/5/2016           20        -3        41                 30.57   

   VisibilityMiles  WindSpeedMPH PrecipitationIn  CloudCover Events  \
0               10           8.0               0           5    NaN   
1               10           7.0               0           3    NaN   
2               10           8.0               0           1    NaN   
3               10           9.0               0           3    NaN   
4               10           5.0               0           0    NaN   

   WindDirDegrees  
0             281  
1             275  
2             277  
3             345  
4             333

In [ ]:


df.Temperature



0     38
1     36
2     40
3     25
4     20
5     33
6     39
7     39
8     44
9     50
10    33
11    35
12    26
13    30
14    43
15    47
16    36
17    25
18    22
19    32
20    31
21    26
22    26
23    28
24    34
25    43
26    41
27    37
28    36
29    34
30    46
Name: Temperature, dtype: int64

In [ ]:


df['Temperature'].max()



50

In [ ]:
df['EST'][df['Events']=='Rain']

8      1/9/2016
9     1/10/2016
15    1/16/2016
26    1/27/2016
Name: EST, dtype: object

In [ ]:
m=df['WindSpeedMPH'].mean()
print(m)

6.892857142857143


In [ ]:
df.isnull().sum()

EST                      0
Temperature              0
DewPoint                 0
Humidity                 0
Sea Level PressureIn     0
VisibilityMiles          0
WindSpeedMPH             3
PrecipitationIn          0
CloudCover               0
Events                  22
WindDirDegrees           0
dtype: int64

In [ ]:
from google.colab import drive
drive.mount('/content/drive')